version: "3"

services:
  voicerPostgres:
    container_name: voicer_pg
    image: postgres:14.1-alpine3.15
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: voicer
      POSTGRES_PASSWORD: '@Voicerprj01'
      POSTGRES_DB: voicerPg

  voicerMongoReader:
    container_name: voicer_mongoReader
    image: mongo:4.4.10
    restart: unless-stopped
    volumes:
      - mongoReader-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=wis
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 28000:27017

  voicerMongoWriter:
    container_name: voicer_mongoWriter
    image: mongo:4.4.10
    restart: unless-stopped
    volumes:
      - mongoWriter-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=wis
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 28001:27017

  voicerApi:
    image: antoniocenteno/voicer-api
    container_name: voicer_api
    restart: unless-stopped
    env_file:
      - ./.env-voicer-api
    tty: true
    ports:
      - 3500:3000
    depends_on:
      - voicerPostgres

  voicerBackendWeb:
    image: antoniocenteno/voicer-backend-web
    container_name: voicer_backendWeb
    restart: unless-stopped
    env_file:
      - ./.env-voicer-backend-web
    tty: true
    ports:
      - 3030:3000
    depends_on:
      - voicerPostgres
  
  voicerWeb:
    image: antoniocenteno/voicer-web
    container_name: voicer_web
    restart: unless-stopped
    env_file:
      - ./.env-voicer-web
    tty: true
    ports:
      - 8080:5000
    depends_on:
      - voicerApi
      - voicerBackendWeb

  voicerOrchestratorServer:
    image: antoniocenteno/voicer-orchestrator-server
    container_name: voicer_orchestratorServer
    restart: unless-stopped
    volumes:
      - sqlite-data:/dist/sqlite/database
    env_file:
      - ./.env-voicer-orchestrator-server
    ports:
      - 3333:3000
      - 9001:9000

  voicerMongoServer:
    image: antoniocenteno/voicer-mongo-server
    container_name: voicer_mongoServer
    restart: unless-stopped
    volumes:
      - sqlite-data:/dist/infra/database
    env_file:
      - ./.env-voicer-mongo-server
    ports:
      - 9002:9000

  voicerOracleServer:
    image: antoniocenteno/voicer-oracle-server
    container_name: voicer_oracleServer
    restart: unless-stopped
    env_file:
      - ./.env-voicer-oracle-server
    ports:
      - 9003:9000

  voicerReader:
    image: antoniocenteno/voicer-reader
    container_name: voicer_reader
    restart: unless-stopped
    env_file:
      - ./.env-voicer-reader
    tty: true
    depends_on:
      - voicerOrchestratorServer
      - voicerMongoServer
      - voicerOracleServer

  voicerWriter:
    image: antoniocenteno/voicer-writer
    container_name: voicer_writer
    restart: unless-stopped
    env_file:
      - ./.env-voicer-writer
    tty: true
    depends_on:
      - voicerOrchestratorServer
      - voicerMongoServer
      - voicerOracleServer

volumes:
  mongoReader-data:
  mongoWriter-data:
  postgres-data:
  sqlite-data:
